Make a change in `package.json`
But don't `bun install` and commit the updated lockfile.

Running `bun install --frozen-lockfile` locally on the contents
of this commit gives the expected error:

```
bun install v1.1.10 (5102a944)
error: lockfile had changes, but lockfile is frozen
note: try re-running without --frozen-lockfile and commit the updated lockfile
```

Let's see what CI says...